### ISSUE TITLE
DIの方法が誤っているため、Serviceインスタンスが複数存在する

### ISSUE THREAD

**Issue by Futty93** [Futty93/Horus#20]
AirspaceManagementImpl.java内のNextStep()が毎秒1回呼び出される想定だが2回呼び出されている。(0.5秒に1回ではなく、1秒ごとに2回ほぼ同時に呼ばれている。)

**Comment by charlie-to** [comment]
見てみたところ、senario service のインスタンスが２つ存在するよう。
２つservice があるから２回呼ばれている。
１秒間に１回実行するメソッドを持つインスタンスが２つ生成されるためほぼ同時に２回呼ばれることになる。

どこで２つ生成されてしまっているかは不明
あとで調べます。

**Comment by Futty93** [comment]
俺も原因が見つけられなかったから丸投げしてしまった。

**Comment by charlie-to** [comment]
DIの仕方が違うっぽいことが[ドキュメント](https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html)を読んでわかった
